version: '3.4'

services:
  learningplatform.api:
    image: ${DOCKER_REGISTRY-}learningplatformapi
    build:
      context: .
      dockerfile: LearningPlatform.API/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
  learningplatform.postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  learningplatform.seq:
    image: datalust/seq
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

volumes:
  postgres-data:
